name: Start RDP Server on Windows

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-2022

    steps:
    - name: Download and setup ngrok
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive -Path "ngrok.zip" -DestinationPath "$PWD\ngrok"
        Move-Item -Path "$PWD\ngrok\ngrok.exe" -Destination "C:\ngrok.exe"

    - name: Authenticate ngrok
      run: C:\ngrok.exe authtoken YOUR_NGROK_AUTH_TOKEN_HERE

    - name: Enable Remote Desktop and Firewall Rules
      run: |
        Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Start ngrok
